# Generated by Django 6.0.5 on 2026-05-16 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Rating cannot be less than 1.'), django.core.validators.MaxValueValidator(5, message='Rating cannot be greater than 5.')], verbose_name='Rating')),
            ],
        ),
    ]
